sidebar:
  title: "&a&lmc.iamtakagi.net"
  lines:
    - "&r{PING}ms"
    - "&r{WORLD}"
    - "&r{WORLD_DATE} {WORLD_TIME} ({WEATHER})"
    - "&r{X}, {Y}, {Z} ({DIRECTION})"
    - "&r{TPS}TPS"
    - "&r{USAGE_RAM} / {TOTAL_RAM} MB"
    - "&7{DATE}"
    - "&7{TIME}"
  pattern:
    date: yyyy/MM/dd
    time: HH:mm:ss
    world_date: yyyy/MM/dd
    world_time: HH:mm